### ISSUE TITLE
GPU debugging  in managedCuda

### ISSUE THREAD

**Issue by luc-como** [kunzmi/managedCuda#1]
Hello Michael, I have recently started learning CUDA programming and I am interested in using it within the .NET framework. I know that NVIDIA NSight provides tools for debugging and profiling the GPU code.
Do you have suggestions on how to do that with managedCUDA?
Thanks for your help!

**Comment by kunzmi** [comment]
There's in principle no difference between debugging and profiling CUDA applications written for/with managedCuda and a straight forward native application. But a few things should be considered:
- The latest NSight version 5 seems to have some problems with managed applications, see for example http://stackoverflow.com/questions/33632738/profiling-managedcuda-in-nsight-or-visual-profiler/ version 4.7 of NSight runs fine for everything Cuda related.
- You need to call CudaContext.ProfilerStop() before ending your application or destroying your context in order to flush the collected data to host.
- For debugging you need of course to compile the kernels with debug info (-G flag for NVCC). Set a breakpoint in your cu-file and Cuda debugger will stop there just as any other debugger would do.
