### ISSUE TITLE
Does this library interface the full CUDA API?

### ISSUE THREAD

**Issue by thanasio** [kunzmi/managedCuda#10]
Hi my question is whether can do the following with 'managed Cuda for c#':

-> Use streams and run kernels on different streams asynchronously.
-> Interface with thrust

Thanks,
T

**Comment by kunzmi** [comment]
Hi,
the CUDA API is fully implemented and streams and asynchronous kernel execution are of course supported. Thrust, on the other hand, is a header only C++ library, which means that there's no DLL that one could link to at runtime, thus there's no support for that in managedCuda.

Michael

**Comment by thanasio** [comment]
Is there a more comprehensive documentation than the one available at wiki? The only ones i could find so far were too simplistic and basic!

Thanks,
T

**Comment by kunzmi** [comment]
In the [release](https://github.com/kunzmi/managedCuda/releases) section you'll find a compiled API documentation and a few samples from the original CUDA Toolkit ported to managedCuda.

**Comment by thanasio** [comment]
thanks!

**Comment by lorenzoviola** [comment]
Hello Michael

I see that this issue is closed, but I try anyway...

Anything changed about thrust since Jan 2016, with cuda 8.0 ?

it would be great to be able to run kernels with Thrust included directly from ManagedCuda


Any hope on this side ?
If so, do you have any working sample of ManagedCuda with thrust ?

By the way I'm trying to run this particular kernel :

https://github.com/thrust/thrust/blob/master/examples/bounding_box.cu


Best Regards
