### ISSUE TITLE
Reduction

### ISSUE THREAD

**Issue by Darren996** [kunzmi/managedCuda#11]
This is awesome stuff!   Hey is there a reduction function somewhere?  I see a reduction in the NPP stuff but is there a plain old reduction?

**Comment by kunzmi** [comment]
Hi, no there's no other reduction implemented "inside" CUDA other than in NPP. As managedCuda only aims to wrap the API itself and doesn't provide features beyond the API, you have to implement the reduction yourself. But using this awesome performence tuning walk-through from Mark Harris, this is quiet straight forward: [reduction.pdf](http://developer.download.nvidia.com/assets/cuda/files/reduction.pdf). There's also an update for newer hardware features on the parallel for all blog: [click me](https://devblogs.nvidia.com/parallelforall/faster-parallel-reductions-kepler/).

Michael

**Comment by Darren996** [comment]
Hey!  Thanks man!

That's the one in the CUDA examples.  I'm trying to get the PTX out of it but it isn't working.  I'm not the sharpest coder in the world. :D I guess I need to break the kernels out one at a time?

Darren

**Comment by kunzmi** [comment]
Just a little hint: all you need ist the cu file from the sample compiled as ptx and then reimplement the template instantation part for "whichKernel==6" in C#. To get the mangled kernel names (used for the templates) just open the compiled ptx code in a text editor. Instead of calling a kernel with "reduce<T, 512, true>..." you call the correspondend kernel with the right mangled name. NVCC will create a different name for every single case for you.

Hope it helps,
Michael

**Comment by Darren996** [comment]
I tried changing it to ptx like the managedcuda samples but it doesn't generate the ptx.  It makes me sad. :D

**Comment by Darren996** [comment]
I think I'm figuring out what you said Michael.  The reduce6 kernel is the one I should be using all the time right?

**Comment by kunzmi** [comment]
Exactly, the other kernels are just the different stages of optimization of the linked pdf. "Reduce6" is the final one and gives you best performence.

**Comment by Darren996** [comment]
Thanks man!
