### ISSUE TITLE
Setup new project issue

### ISSUE THREAD

**Issue by archiseb** [kunzmi/managedCuda#12]
Dear Michael,

I'm beginner in C# - CUDA projects. I was very happy when I found your tutorial "Setup-a-managedCuda-project". But when I've changed my CUDARuntime project Configuration Type from dll to Utility (Hilfsprogramm?)  all my #include directive stopped working, and all header files disappear from "External dependencies". So all cuda stuff such a __global__ are undefined...
I'm using VS Pro 2013 
Could you help me. I will be grateful.

**Comment by kunzmi** [comment]
You're probably missing the Cuda include directory in the project settings. Try to add the right cuda  folder to your include folders.
BTW, setting the configuration type to "Utility", or what ever the right English translation is, only disables the Visual C++ compiler as we want NVCC to be used independently (without host code) to create the PTX files. That's why IntelliSense gets a bit confused, but NVCC should always compile properly.

**Comment by archiseb** [comment]
I dont know why, but by swiching to Utility, VS automatically removed all include folder associated with CUDA. Thank you.
