### ISSUE TITLE
The ger method has caused me some trouble

### ISSUE THREAD

**Issue by mrakgr** [kunzmi/managedCuda#24]
public void Ger(float alpha, CudaDeviceVariable<float> x, int incx, CudaDeviceVariable<float> y, int incy, CudaDeviceVariable<float> A, int lda)
		{
			_status = CudaBlasNativeMethods.cublasSger_v2(_blasHandle, x.Size, y.Size, ref alpha, x.DevicePointer, incx, y.DevicePointer, incy, A.DevicePointer, lda);
			Debug.WriteLine(String.Format("{0:G}, {1}: {2}", DateTime.Now, "cublasSger_v2", _status));
			if (_status != CublasStatus.Success) throw new CudaBlasException(_status);
		}

More specifically, the `x.Size, y.Size` part. It seems quite innocuous, but in my ML library I would often reuse memory by pretending the CudaDeviceVariable is smaller than it actually is. So when I pass it into ger, the function would get the actual size directly via the pointer and throw an invalid value error.

I'd suggest the API be changed to something like:

		public void Ger(int m, int n, float alpha, CudaDeviceVariable<float> x, int incx, CudaDeviceVariable<float> y, int incy, CudaDeviceVariable<float> A, int lda)
		{
			_status = CudaBlasNativeMethods.cublasSger_v2(_blasHandle, m, n, ref alpha, x.DevicePointer, incx, y.DevicePointer, incy, A.DevicePointer, lda);
			Debug.WriteLine(String.Format("{0:G}, {1}: {2}", DateTime.Now, "cublasSger_v2", _status));
			if (_status != CublasStatus.Success) throw new CudaBlasException(_status);
		}

I think I recall the library doing something similar to the above in a different method, which caused me trouble in the past, but I can't quite recall at the moment. Rather than break the API to fix this, it might be better to make extra methods and I could make them myself if you want.

**Comment by kunzmi** [comment]
Actually your suggestion would break the initial idea of managedCuda: I don't want to handle the allocation sizes manually at any moment! Further, your proposed `Ger` variant doesn't simplify its use, the parameter count is practically as long as the raw API call to cublas. In my eyes your suggestion has too limited improvements compared to a raw API call.

But in order to handle different allocation sizes with the existing API, managedCuda offers you a smarter way to solve your problem: CudaDeviceVariable can also handle existing allocations and give you sort of a limited "view" to the underlying allocation. Allocate some memory on GPU and then create a view with another CudaDeviceVariable to it:
```
CudaDeviceVariable<float> bigAllocation = new CudaDeviceVariable<float>(1024);
CudaDeviceVariable<float> partialView = new CudaDeviceVariable<float>(bigAllocation.DevicePointer, 512 * bigAllocation.TypeSize);
partialView.Dispose(); //won't do anything as partialView is not the owner of the initial allocation.
bigAllocation.Dispose(); //will free everything.
```

and then use `partialView` with the existing API of cudaBlas.
Of course there might be other methods in the library where `m` or `n` are used as parameters and aren't given by another CudaDeviceVariable. Either this is not intended and should be fixed or the the values are not directly related, e.g. in case when `n` is `size - 1` without checking for zero...

**Comment by mrakgr** [comment]
What I meant to say was that since gemm, gemv, geam and such have `m` and `n` parameters in the public API that maybe having ger have the same signature would not be bad either. There, the allocations sizes are in fact handled manually.

**Comment by mrakgr** [comment]
Actually, now I see that you said it is not as intended. That said, I'd really not recommend changing the API for the aforementioned functions. Gemm for example requires some crazy rotations to work correctly that I only discovered it by accident. Here is how it looks like in my library.

```
    let a_col = if transa = nT then cols A else rows A
    let b_row = if transb = nT then rows B else cols B
    if a_col <> b_row then failwithf "a_col(%i) <> b_row(%i) in gemm!" a_col b_row
    let m = if transa = nT then rows A else cols A
    let n = if transb = nT then cols B else rows B
    let k = a_col
    let lda = if transa = nT then m else k
    let ldb = if transb = nT then k else n
    let ldc = m

    if m <> rows C || n <> cols C then failwithf "m(%i) <> rows C(%i) || n(%i) <> cols C(%i)" m (rows C) n (cols C)

    cublas.Gemm(transa, transb, m, n, k, alpha, ext_a A, lda, ext_b B, ldb, beta, ext_c C, ldc)
```

At any rate, this is not really an issue for me anymore as just reached for ger through the CudaBlasNativeMethods directly.

The fact that you said it is not as intended is a surprise to me as the only functions I've been using were really gemm and geam. Just recently I added gemv and ger.

**Comment by mrakgr** [comment]
Let me close this issue. On further thought, if you want to change the API for gemm, gemv, geam to be as intended go ahead. It would not trouble me at all to change the wrapper functions for those 3 to use the native methods directly. I was just surprised.
